org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

mod_id=moni_ldlib_patch
mod_version=0.0
mod_name=Monifactory LDLib Patch
mod_description=A patch to SelectorWidget in LDLib mod for Minecraft modpack Monifactory.
mod_license=GPL-3.0-or-later
mod_author=Myitian
mod_source=https://github.com/Myitian/MonifactoryLDLibPatch

maven_group=net.myitian.moni_ldlib_patch

version_id=1.20.1
minecraft_version=1.20.1
parchment_mappings=1.20.1:2023.09.03

enabled_platforms=forge
fabric_loader_version=0.17.3
forge_version=1.20.1-47.4.10